// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWYCNyiSNjW6pTPLBOA17EBLIwgODmr0',
    appId: '1:887355401922:web:867f9e09ac7c434ffc3d5b',
    messagingSenderId: '887355401922',
    projectId: 'chat-app-8f046',
    authDomain: 'chat-app-8f046.firebaseapp.com',
    storageBucket: 'chat-app-8f046.appspot.com',
    measurementId: 'G-5Y51S0SNTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLpb9rQzp8eI4nnFYicfaDa0_J86vs6mo',
    appId: '1:887355401922:android:08c7afbb15d14172fc3d5b',
    messagingSenderId: '887355401922',
    projectId: 'chat-app-8f046',
    storageBucket: 'chat-app-8f046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZxdD2BwTFMyFEprtOj5-YFbvhvHFMmc',
    appId: '1:887355401922:ios:5c47c802790b7372fc3d5b',
    messagingSenderId: '887355401922',
    projectId: 'chat-app-8f046',
    storageBucket: 'chat-app-8f046.appspot.com',
    iosBundleId: 'com.example.scholarChattest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZxdD2BwTFMyFEprtOj5-YFbvhvHFMmc',
    appId: '1:887355401922:ios:dc046b3430041a84fc3d5b',
    messagingSenderId: '887355401922',
    projectId: 'chat-app-8f046',
    storageBucket: 'chat-app-8f046.appspot.com',
    iosBundleId: 'com.example.scholarChattest.RunnerTests',
  );
}
